# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91d49864fe8f488622cae71ff61b1506b6b96c07a262d25f6eaffc440f65ff25565c17c6dfe27c7a048c823ed737ecbe06ecd433bf32407481499f10370ca155

test:
  secret_key_base: bb7c34583cff1a6d4da2b9a81fef0a51bf7e601aadb96709e70bac04b8e19fbba4dddb4321e2776644d7bba52de81f45832062ee351d9d3fdb0473f5a8df2304

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
